GET http://localhost:5000/api/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZjMWYxODdlOTRlNmUxMmZkMjMyOWEiLCJlbWFpbCI6ImphbmUuZG9lQGdtYWlsLmNvbSIsImlhdCI6MTcxODcwOTE1OCwiZXhwIjoxNzE4NzEyNzU4fQ.nY1uOMaQUER3VhDgHAdeF8aMZumUhnfw_n-ghES8Sjc


