POST http://localhost:5000/api/tasks/
Content-Type: application/json

{
    "authorId": "666c1e3a2d5f898c2a773263",
    "body": "Заварити чай",
    "createdAt": "2024-06-14",
    "deadLine": "2024-06-14",
    "status": "done"
    
}
