DELETE http://localhost:5000/api/tasks/6679673f133804de7359b2ca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZjMWUzYTJkNWY4OThjMmE3NzMyNjMiLCJlbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsImlhdCI6MTcxOTIzNzQ5MywiZXhwIjoxNzE5MjM3NTUzfQ.JykmV3m007pkm0DsFlwE4w2TgUWxyW8n9kwbifUfSFo